# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
#
HEADER_DIR=$(top_builddir)/headers

BPF_EXTRA_INCLUDES = \
	bpf/bpf_trace_helpers.h \
	bpf/compiler.h \
	linux/bpf.h \
	linux/bpf_common.h \
	linux/btf.h \
	linux/err.h \
	linux/if_link.h \
	linux/if_xdp.h \
	linux/netlink.h \
	linux/perf-sys.h \
	vmlinux/arch/arm64/vmlinux.h \
	vmlinux/powerpc/vmlinux.h \
	vmlinux/x86/vmlinux.h \
	vmlinux/vmlinux_arch.h \
	vmlinux/vmlinux_common.h \
	vmlinux/vmlinux_net.h \
	vmlinux/vmlinux_types.h \
	vmlinux_local.h
